version: '3'

services:
  app:
    networks:
      itea-test:
        ipv4_address: 172.29.0.8
    container_name: itea_app_php
    image: volkulion/itea_laravel:latest
    volumes:
    - ./:/src/:delegated
    environment:
      NODE_ENV: "development"
      XDEBUG_DEBUG: "off"
      XDEBUG_PROFILE: "off"
    expose:
    - "80"
    ports:
    - 8081:80
  nginx:
    networks:
      itea-test:
        ipv4_address: 172.29.0.10
    container_name: itea_nginx
    image: nginx:stable
    expose:
    - "80"
    ports:
    - 127.0.0.1:80:80
    volumes:
    - ./docker/helpers/nginx/conf.d:/etc/nginx/conf.d/:delegated

  mariadb:
    networks:
      itea-test:
        ipv4_address: 172.29.0.3
    container_name: itea_mariadb
    image: mariadb:10.3
    expose:
    - "3306"
    ports:
    - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "itea"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    volumes:
    - ./docker/helpers/mariadb/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:delegated
    - mysqldb:/var/lib/mysql:delegated

  redis:
    networks:
      itea-test:
        ipv4_address: 172.29.0.4
    container_name: itea_redis
    image: launcher.gcr.io/google/redis4
    command: ["/etc/redis/redis.conf"]
    expose:
    - "6379"
    ports:
    - "6379:6379"
    volumes:
    - redis:/data:delegated
    - ./docker/helpers/redis/redis.conf:/etc/redis/redis.conf:delegated

networks:
  itea-test:
    external: true

volumes:
  mysqldb:
  redis:
