apiVersion: apps/v1
kind: Deployment
metadata:
  name: itea-deploy-qa1
  labels:
    app: itea-laravel-qa1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itea-laravel-qa1
  template:
    metadata:
      labels:
        app: itea-laravel-qa1
    spec:
      containers:
      - name: itea
        image: volkulion/itea_laravel_qa1:latest
        ports:
        - name: default
          containerPort: 80
        resources:
        env:
        - name: laravel-app-pod
          value: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: itea-laravel-qa1
spec:
  selector:
    app: itea-laravel-qa1
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer