apiVersion: apps/v1
kind: Deployment
metadata:
  name: itea-deploy
  labels:
    app: itea-laravel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itea-laravel
  template:
    metadata:
      labels:
        app: itea-laravel
    spec:
      containers:
      - name: itea
        image: volkulion/itea_laravel
        ports:
        - name: default
          containerPort: 80
        resources:
        env:
            - name: laravel-app-pod
              value: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: itea-laravel
spec:
  selector:
    app: itea-laravel
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  


 